version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  project: Collabitama.sln
  parallel: true
  verbosity: normal
test:
  assemblies:
    only:
    - Collabitama.Tests.dll
deploy: off